### ISSUE TITLE
Грешка приликом покретања апликације на Windows-у

### ISSUE THREAD

**Issue by sivancev** [zenariworks/crkva#14]
sasa.ivancev@mcmm /e/projects/crkva
$ docker compose run --rm app sh -c "python manage.py loaddata registar"
 Container crkva-db-1  Running
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/serializers/python.py", line 178, in Deserializer
    data[field.name] = field.to_python(field_value)
  File "/py/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1430, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['Вредност "2023-10-27T20:52:58Z" нема исправан формат датума. Мора бити у формату ГГГГ-ММ-ДД.']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/py/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/py/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/py/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/py/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/py/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 251, in load_label
    for obj in objects:
  File "/py/lib/python3.9/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/py/lib/python3.9/site-packages/django/core/serializers/python.py", line 180, in Deserializer
    raise base.DeserializationError.WithData(
django.core.serializers.base.DeserializationError: Problem installing fixture '/app/fixtures/registar.json': ['Вредност "2023-10-27T20:52:58Z" нема исправан формат датума. Мора бити у формату ГГГГ-ММ-ДД.']: (registar.osoba:pk=08b26707-2767-42c6-9d52-9f18d2187761) field_value was '2023-10-27T20:52:58Z'

У Readme фајлу фали који је тачан формат датума који се очекује.

**Comment by zenfiric** [comment]
Ово је део старог начина уноса података. Више се не користи, тако да затварам задатак
