### ISSUE TITLE
Унос нове особе у табели крштења

### ISSUE THREAD

**Issue by sivancev** [zenariworks/crkva#23]
Покушао сам да додам нови рекорд у табели Крштења - за то дете у табели Парохијани није постојало име оца, мајке и кума. 
Додао сам сва 3 имена, попунио сва тражена поља, на Сачувај:

![image](https://github.com/zenariworks/crkva/assets/5973854/b377cbbf-e7b9-41c0-9cbf-2983ca255749)

добијам следећу грешку:

Environment:

Request Method: POST
Request URL: http://localhost:8000/admin/registar/krstenje/add/

Django Version: 4.2.11
Python Version: 3.10.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'registar',
 'import_export',
 'django_select2',
 'admin_searchable_dropdown']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/py/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "dete_majci" of relation "krstenja" violates not-null constraint
DETAIL:  Failing row contains (262117b8-a997-42b6-929a-b97e116590cc, 4, 16, 120, null, 2017-03-22, 02:00:00, null, null, null, , null, 5ad596e3-d943-437e-a3c6-4af47a8ddcd9, 52999a17-c8cf-4b55-a11e-07c4b2db9b5f, 06b8e52a-580e-4e99-a44f-ceac7af2e37b, 9e04a9bc-d2cd-4e60-9242-779db7dd8177, 5f913adb-f924-46ba-91dc-d754d1751d05, 8044f7d5-f3b4-44d9-9b5a-21e7f27e2e33).
) was the direct cause of the following exception:
  File "/py/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/py/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/py/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/py/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/py/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1227, in save_model
    obj.save()
  File "/py/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/py/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/py/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/py/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/py/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/py/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/py/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/py/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/py/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/py/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/py/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/py/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/py/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /admin/registar/krstenje/add/
Exception Value: null value in column "dete_majci" of relation "krstenja" violates not-null constraint
DETAIL:  Failing row contains (262117b8-a997-42b6-929a-b97e116590cc, 4, 16, 120, null, 2017-03-22, 02:00:00, null, null, null, , null, 5ad596e3-d943-437e-a3c6-4af47a8ddcd9, 52999a17-c8cf-4b55-a11e-07c4b2db9b5f, 06b8e52a-580e-4e99-a44f-ceac7af2e37b, 9e04a9bc-d2cd-4e60-9242-779db7dd8177, 5f913adb-f924-46ba-91dc-d754d1751d05, 8044f7d5-f3b4-44d9-9b5a-21e7f27e2e33).

**Comment by zenfiric** [comment]
## Провера (2026-06-03)

Оригинална грешка (`IntegrityError: null value in column "dete_majci" violates not-null constraint`) **више се не репродукује**.

Шта се променило:
- Модел `Krstenje` је рефакторисан — поље `dete_majci` више не постоји. Отац/мајка/кум су сада опциони (`null=True`) FK ка `Osoba`, а „по реду мајци" је текстуално поље (`po_redu`).
- Унос је пребачен са Django admin-а на наменску форму (`KrstenjeForm` + `krstenje.html`), уз модал за брзи унос нове особе (`_modal_osoba.html`) — па отац/мајка/кум који не постоје могу да се додају у ходу.

Тест на живој бази (парохија Чукарица): чување крштења **без** оца/мајке/кума пролази без грешке.

⚠️ Пре затварања потребно је још потврдити цео ток кроз UI на живој инстанци (унос новог детета + 3 нове особе → Сачувај). Остаје отворено до те потврде.

**Comment by zenfiric** [comment]
**Решено.** ✅

Грешка из пријаве (`null value in column "dete_majci" ... violates not-null constraint` на `POST /admin/registar/krstenje/add/`) више није могућа:

- Колона `dete_majci` **више не постоји**. У актуелној табели `krstenja` једина обавезна (`NOT NULL`) поља су протоколарна (`uid`, `godina_registracije`, `redni_broj`, `knjiga`, `strana`, `broj`) и логичка поља са подразумеваном вредношћу (`zivorodjeno`, `vanbracno`, `blizanac`, `telesna_mana`). Некадашње „по реду мајци“ је сада `po_redu` → **није обавезно**.
- Све особе у крштењу (`dete`, `otac`, `majka`, `kum`) су опциони FK-ови (`null=True, blank=True`).
- Стари Django-admin унос (`admin_searchable_dropdown`) замењен је наменском формом `KrstenjeForm` са правом валидацијом (иста особа не може бити у две улоге; име близанца обавезно ако је означен близанац).

Поред исправке пада, **првобитни циљ — унос нове особе из табеле крштења — сада ради**: поља за особе (`OsobaSelect2Widget` и М/Ж варијанте) приказују футер „**+ Додај нову особу**“ у падајућој листи. Клик отвара модал `#osoba-modal`, дели уписани текст на Име/Презиме и унапред бира пол према пољу (отац→М, мајка→Ж) — нову особу је могуће додати без напуштања форме.

Затварам издање.
